// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXou-TEQB9-TdHgyth_GvQE7qRMRMoGjs',
    appId: '1:561789105103:web:7023f261c133f43b0e98ba',
    messagingSenderId: '561789105103',
    projectId: 'rentapp-24c82',
    authDomain: 'rentapp-24c82.firebaseapp.com',
    storageBucket: 'rentapp-24c82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyr_Fd4hhq5AtcxhdbaIA9rH349WnC5ck',
    appId: '1:561789105103:android:1cb9e985776d5ca40e98ba',
    messagingSenderId: '561789105103',
    projectId: 'rentapp-24c82',
    storageBucket: 'rentapp-24c82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__49ZAzKEgGAEGNAZfkbj7Sr2o6OqIrU',
    appId: '1:561789105103:ios:74a074e6a727dbe30e98ba',
    messagingSenderId: '561789105103',
    projectId: 'rentapp-24c82',
    storageBucket: 'rentapp-24c82.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB__49ZAzKEgGAEGNAZfkbj7Sr2o6OqIrU',
    appId: '1:561789105103:ios:74a074e6a727dbe30e98ba',
    messagingSenderId: '561789105103',
    projectId: 'rentapp-24c82',
    storageBucket: 'rentapp-24c82.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXou-TEQB9-TdHgyth_GvQE7qRMRMoGjs',
    appId: '1:561789105103:web:5a5396e76ee1c42d0e98ba',
    messagingSenderId: '561789105103',
    projectId: 'rentapp-24c82',
    authDomain: 'rentapp-24c82.firebaseapp.com',
    storageBucket: 'rentapp-24c82.firebasestorage.app',
  );
}
